const LOGIN = {
  LOGIN_REQUEST_GET: "LOGIN/LOGIN_REQUEST_GET",
  LOGIN_SUCCESS_GET: "LOGIN/LOGIN_SUCCESS_GET",
  LOGIN_FAILURE_GET: "LOGIN/LOGIN_FAILURE_GET",
  LOGOUT_REQUEST_GET: "LOGIN/LOGOUT_REQUEST_GET",
  LOGOUT_SUCCESS_GET: "LOGIN/LOGOUT_SUCCESS_GET",
  LOGOUT_FAILURE_GET: "LOGIN/LOGOUT_FAILURE_GET",
  CLEAR_AUTH_ERROR_GET: "LOGIN/CLEAR_AUTH_ERROR_GET",
}

export { LOGIN };
